//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_NET_Exam_BookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.CustomersBooks = new HashSet<CustomersBooks>();
            this.Decommissed = new HashSet<Decommissed>();
            this.DiscountBooks = new HashSet<DiscountBooks>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> SelfPrice { get; set; }
        public System.DateTime ProdactionDate { get; set; }
        public Nullable<int> Pages { get; set; }
        public int Availability { get; set; }
        public int AuthorId { get; set; }
        public int PublisherId { get; set; }
        public int ThemeId { get; set; }
        public Nullable<int> SeriesId { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Publishers Publishers { get; set; }
        public virtual Series Series { get; set; }
        public virtual Themes Themes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomersBooks> CustomersBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Decommissed> Decommissed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountBooks> DiscountBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
