//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_NET_Exam_BookStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookstoreEntEntities : DbContext
    {
        public BookstoreEntEntities()
            : base("name=BookstoreEntEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<CustomersBooks> CustomersBooks { get; set; }
        public virtual DbSet<Decommissed> Decommissed { get; set; }
        public virtual DbSet<DiscountBooks> DiscountBooks { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
    }
}
